package Entities;
// Generated 16/05/2016 07:45:32 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name="categoria"
    ,schema="public"
)
public class Categoria  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String icono;
     private Set referenciaOmbus = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(int id) {
        this.id = id;
    }
    public Categoria(int id, String nombre, String icono, Set referenciaOmbus) {
       this.id = id;
       this.nombre = nombre;
       this.icono = icono;
       this.referenciaOmbus = referenciaOmbus;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="icono", length=1000)
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoria")
    public Set getReferenciaOmbus() {
        return this.referenciaOmbus;
    }
    
    public void setReferenciaOmbus(Set referenciaOmbus) {
        this.referenciaOmbus = referenciaOmbus;
    }




}


