package Entities;
// Generated 16/05/2016 07:45:32 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Ombues generated by hbm2java
 */
@Entity
@Table(name="ombues"
    ,schema="public"
)
public class Ombues  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private String direccion;
     private String ubicacion;
     private String externalRef;
     private ZonaOmbu zonaOmbu;
     private ReferenciaOmbu referenciaOmbu;
     private PuntoOmbu puntoOmbu;

    public Ombues() {
    }

	
    public Ombues(int id) {
        this.id = id;
    }
    public Ombues(int id, String nombre, String descripcion, String direccion, String ubicacion, String externalRef, ZonaOmbu zonaOmbu, ReferenciaOmbu referenciaOmbu, PuntoOmbu puntoOmbu) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.direccion = direccion;
       this.ubicacion = ubicacion;
       this.externalRef = externalRef;
       this.zonaOmbu = zonaOmbu;
       this.referenciaOmbu = referenciaOmbu;
       this.puntoOmbu = puntoOmbu;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="nombre", length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="direccion", length=30)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="ubicacion", length=200)
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

    
    @Column(name="external_ref", length=100)
    public String getExternalRef() {
        return this.externalRef;
    }
    
    public void setExternalRef(String externalRef) {
        this.externalRef = externalRef;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="ombues")
    public ZonaOmbu getZonaOmbu() {
        return this.zonaOmbu;
    }
    
    public void setZonaOmbu(ZonaOmbu zonaOmbu) {
        this.zonaOmbu = zonaOmbu;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="ombues")
    public ReferenciaOmbu getReferenciaOmbu() {
        return this.referenciaOmbu;
    }
    
    public void setReferenciaOmbu(ReferenciaOmbu referenciaOmbu) {
        this.referenciaOmbu = referenciaOmbu;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="ombues")
    public PuntoOmbu getPuntoOmbu() {
        return this.puntoOmbu;
    }
    
    public void setPuntoOmbu(PuntoOmbu puntoOmbu) {
        this.puntoOmbu = puntoOmbu;
    }




}


