package Entities;
// Generated 16/05/2016 07:45:32 PM by Hibernate Tools 4.3.1


import com.vividsolutions.jts.geom.Point;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.annotations.Type;

/**
 * PuntoOmbu generated by hbm2java
 */
@Entity
@Table(name="punto_ombu"
    ,schema="public"
)
public class PuntoOmbu  implements java.io.Serializable {


@Column(name="id", unique=true, nullable=false)
     private Integer id;
     @OneToOne(fetch=FetchType.LAZY)
     private Ombues ombues;
      
     @Type(type="org.hibernate.spatial.GeometryType")
     private Point geom;

    public PuntoOmbu() {
    }

	
    public PuntoOmbu(Ombues ombues) {
        this.ombues = ombues;
    }
    public PuntoOmbu(Ombues ombues, Point geom) {
       this.ombues = ombues;
       this.geom = geom;
    }
   

    
@Id
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@PrimaryKeyJoinColumn
    public Ombues getOmbues() {
        return this.ombues;
    }
    
    public void setOmbues(Ombues ombues) {
        this.ombues = ombues;
    }

    
    public Point getGeom() {
        return this.geom;
    }
    
    public void setGeom(Point geom) {
        this.geom = geom;
    }

    @Override
    public String toString() {
        return "PuntoOmbu{" + "id=" + id + ", ombues=" + ombues + ", geom=" + geom + '}';
    }




}


